---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.11.2
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cilium
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
