# https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml

devices: [wlp2s0]
hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
ipam:
  mode: kubernetes
k8sServiceHost: hominion
k8sServicePort: 6443
ipv4NativeRoutingCIDR: 10.42.0.0/15
kubeProxyReplacement: strict
operator:
  rollOutPods: true
  replicas: 1
tunnel: disabled
