---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nitter
  namespace: nitter
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: morremeyer
        namespace: flux-system
      version: 7.0.2
  dependsOn:
    - name: redis
  interval: 5m
  releaseName: nitter
  values:
    # https://github.com/morremeyer/charts/blob/main/charts/generic/values.yaml
    additionalVolumes:
      - name: config
        configMap:
          name: config
    additionalVolumeMounts:
      - name: config
        mountPath: /config
    command:
      - /bin/ash
      - -c
      - |-
        set -ueo pipefail
        sed -e "s/__REDISPASS__/$REDIS_PASSWORD/" \
            -e "s/__HMAC__/$HMAC_TOKEN/" \
          < /config/nitter.conf > /nitter.conf
        exec /src/nitter
    env:
      NITTER_CONF_FILE: /nitter.conf
    envValueFrom:
      REDIS_PASSWORD:
        secretKeyRef:
          name: redis
          key: redis-password
      HMAC_TOKEN:
        secretKeyRef:
          name: hmac
          key: token
    image:
      repository: zedeus/nitter
      tag: bc219aa792cc0e4117888b2036a969559f4f2689-arm64
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: nginx
      hosts:
        - host: nitter.samcday.com
          paths:
            - path: /
              servicePortName: http
      tls:
        - hosts: [nitter.samcday.com]
          secretName: certificate
    livenessProbe:
      httpGet:
        path: /POTUS
    nodeSelector:
      kubernetes.io/arch: arm64
    ports:
      - name: http
        containerPort: 8080
    readinessProbe: ~
    replicaCount: 2
    tolerations:
      - key: samcday.com/cloud
        effect: NoExecute
