apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautrix-telegram
  namespace: synapse
  labels:
    app: mautrix-telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautrix-telegram
  serviceName: mautrix-telegram
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: mautrix-telegram
    spec:
      containers:
        - image: dock.mau.dev/mautrix/telegram:v0.12.1
          name: mautrix-telegram
          ports:
            - containerPort: 29317
          volumeMounts:
            - name: scratch
              mountPath: /data
      initContainers:
        - name: config
          image: supinf/envsubst
          command:
            - sh
            - -c
            - |-
              envsubst < /config-template/mautrix-telegram.yaml > /data/config.yaml
              touch /data/registration.yaml
              chown -cR root:root /data
          env:
            - name: SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: mautrix-telegram
                  key: SHARED_SECRET
            - name: AS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mautrix-telegram
                  key: AS_TOKEN
            - name: HS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mautrix-telegram
                  key: HS_TOKEN
            - name: API_ID
              valueFrom:
                secretKeyRef:
                  name: mautrix-telegram
                  key: API_ID
            - name: API_HASH
              valueFrom:
                secretKeyRef:
                  name: mautrix-telegram
                  key: API_HASH
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: scratch
              mountPath: /data
      volumes:
        - name: config-template
          configMap:
            name: mautrix-telegram
        - name: scratch
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-telegram
  namespace: synapse
  labels:
    app: mautrix-telegram
spec:
  ports:
    - port: 29317
      protocol: TCP
      targetPort: 29317
  selector:
    app: mautrix-telegram
