apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: synapse
  namespace: synapse
spec:
  podMetricsEndpoints:
    - port: ls-metrics
    - port: mau-sig-metrics
    - port: synapse
  selector:
    matchLabels:
      app: synapse
