apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: synapse
  namespace: synapse
spec:
  podMetricsEndpoints:
    - port: ls-metrics
    - port: mau-sig-metrics
    - port: mau-tele-metrics
    - port: mau-wa-metrics
    - port: signald-metrics
    - port: syn-metrics
      path: /_synapse/metrics
  selector:
    matchLabels:
      app: synapse
