apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: synapse
  namespace: synapse
spec:
  podMetricsEndpoints:
    - port: ls-metrics
  selector:
    matchLabels:
      app: synapse
