apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse
  namespace: synapse
  labels:
    app: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  serviceName: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: synapse
    spec:
      containers:
        # - image: dock.mau.dev/mautrix/signal:v0.2.1
        #   name: mautrix-signal
        #   ports:
        #     - containerPort: 29328
        #   volumeMounts:
        #     - name: scratch
        #       mountPath: /data
        #     - name: signald
        #       mountPath: /signald
        # - image: dock.mau.dev/mautrix/telegram:v0.12.1
        #   name: mautrix-telegram
        #   ports:
        #     - containerPort: 29317
        #   volumeMounts:
        #     - name: scratch
        #       mountPath: /data
        # - image: dock.mau.dev/mautrix/whatsapp:v0.2.1
        #   name: mautrix-whatsapp
        #   ports:
        #   - containerPort: 29318
        #   volumeMounts:
        #   - name: data
        #     mountPath: /data
        # - image: signald/signald:0.22.2
        #   name: signald
        #   volumeMounts:
        #     - name: signald
        #       mountPath: /signald
        - image: matrixdotorg/synapse
          name: synapse
          ports:
            - containerPort: 8008
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /config/homeserver.yaml
          volumeMounts:
            - name: config
              mountPath: /config
            - name: signing-key
              mountPath: /signing-key
            - name: data
              mountPath: /data
      initContainers:
        - name: config
          image: supinf/envsubst
          command:
            - sh
            - -c
            - |-
              mkdir -p /data/media
              chown -R 991:991 /data
              cp /config-template/{log.yaml,mautrix-signal.yaml,mautrix-whatsapp.yaml} /config/
              envsubst < /config-template/homeserver.yaml > /config/homeserver.yaml
              envsubst < /config-template/mautrix-telegram.yaml > /config/mautrix-telegram.yaml
          envFrom:
            - secretRef:
                name: synapse-env
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
        # - name: mautrix-signal-register
        #   image: 
        #   command:
        #     - sh
        #     - -c
        #     - |-
        #       touch /data/registration.yaml
      volumes:
        - name: appservices
          emptyDir: {}
        - name: synapse-config-template
          configMap:
            name: config
        - name: config
          emptyDir: {}
        - name: mautrix-signal-config
          configMap:
            name: mautrix-signal
        - name: signing-key
          secret:
            secretName: signing-key
        - name: signald
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: openebs-lvmpv
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
  labels:
    app: synapse
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: synapse
