apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse
  namespace: synapse
  labels:
    app: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  serviceName: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: synapse
    spec:
      containers:
        - image: dock.mau.dev/mautrix/signal:v0.4.0
          name: mautrix-signal
          ports:
            - containerPort: 29328
          volumeMounts:
            - name: data
              mountPath: /db
            - name: mautrix-signal
              mountPath: /data
            - name: data
              mountPath: /signald_data
              subPath: signald
        - image: dock.mau.dev/mautrix/telegram:v0.12.1
          name: mautrix-telegram
          ports:
            - containerPort: 29317
          volumeMounts:
            - name: data
              mountPath: /db
            - name: mautrix-telegram
              mountPath: /data
        - image: dock.mau.dev/mautrix/whatsapp:v0.7.0
          name: mautrix-whatsapp
          env:
            - name: UID
              value: "991"
            - name: GID
              value: "991"
          ports:
            - containerPort: 29318
          volumeMounts:
            - name: data
              mountPath: /db
            - name: mautrix-whatsapp
              mountPath: /data
        - image: signald/signald:0.22.2
          name: signald
          args:
            - -d
            - /data/signald
            - -s
            - /signald/signald.sock
          volumeMounts:
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
        - name: litestream
          image: litestream/litestream:0.3.9
          args: ['replicate']
          volumeMounts: &litestreamvols
            - name: data
              mountPath: /data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          envFrom: &litestreamenv
            - secretRef:
                name: backup-bucket
          ports:
          - name: metrics
            containerPort: 9090
        - image: matrixdotorg/synapse
          name: synapse
          ports:
            - containerPort: 8008
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /config/homeserver.yaml
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: mautrix-signal
              mountPath: /mautrix-signal
            - name: mautrix-telegram
              mountPath: /mautrix-telegram
            - name: mautrix-whatsapp
              mountPath: /mautrix-whatsapp
            - name: signing-key
              mountPath: /signing-key
      initContainers:
        - name: init-litestream-mautrix-synapse
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-signal.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-mautrix-telegram
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-telegram.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-mautrix-whatsapp
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-whatsapp.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-synapse
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/synapse.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-signald
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/signald/signald.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: config
          image: supinf/envsubst
          command:
            - sh
            - -c
            - |-
              mkdir -p /data/media
              mkdir -p /data/signald
              chown -R 991:991 /data
              cp /config-templates/mautrix-signal.yaml /mautrix-signal/config.yaml
              cp /config-templates/mautrix-whatsapp.yaml /mautrix-whatsapp/config.yaml
              envsubst < /config-templates/mautrix-telegram.yaml > /mautrix-telegram/config.yaml
              cp /config-templates/log.yaml /config/
              envsubst < /config-templates/homeserver.yaml > /config/homeserver.yaml
          envFrom:
            - secretRef:
                name: synapse-env
          volumeMounts:
            - name: config-templates
              mountPath: /config-templates
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: mautrix-signal
              mountPath: /mautrix-signal
            - name: mautrix-telegram
              mountPath: /mautrix-telegram
            - name: mautrix-whatsapp
              mountPath: /mautrix-whatsapp
        - name: mautrix-signal-register
          image: dock.mau.dev/mautrix/signal:v0.2.1
          volumeMounts:
            - name: mautrix-signal
              mountPath: /data
        - name: mautrix-telegram-register
          image: dock.mau.dev/mautrix/telegram:v0.12.1
          volumeMounts:
            - name: mautrix-telegram
              mountPath: /data
        - name: mautrix-whatsapp-register
          image: dock.mau.dev/mautrix/whatsapp:v0.2.1
          env:
            - name: UID
              value: "991"
            - name: GID
              value: "991"
          volumeMounts:
            - name: mautrix-whatsapp
              mountPath: /data
      volumes:
        - name: appservices
          emptyDir: {}
        - name: config-templates
          configMap:
            name: config
        - name: config
          emptyDir: {}
        - name: litestream-config
          configMap:
            name: litestream-config
        - name: mautrix-signal
          emptyDir: {}
        - name: mautrix-telegram
          emptyDir: {}
        - name: mautrix-whatsapp
          emptyDir: {}
        - name: signing-key
          secret:
            secretName: signing-key
        - name: signald
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: openebs-lvmpv
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
  labels:
    app: synapse
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: synapse
