apiVersion: v1
kind: Secret
metadata:
    name: token
    namespace: factorio
stringData:
    token: ENC[AES256_GCM,data:T0SNCtzne/ViMOcXPwX9n9M6urFG9m/QqOpdh4dZ,iv:VfivcdGLZWP7rlX/OqUi0VzFgplp3Rs71yqBz2BmAY4=,tag:7NLGPvHu0DhitCm8nlvkLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b0FnZElKdE9ZdkZLTkV1
            OVY1aGh6NnpKQk0vcEdqYVFiQzVXN1JXZkhjCnVkUlkvK2J6cVdtS0plSm9QM3lI
            QVREdmc2NzV5OGM3cVQ5bXlYaU51MlUKLS0tIEtsbHNCTHFieHh2SWdZVHZiSGpV
            bTNobUYvOUJQNW1UT1VGVFhJZDhhaEkK4kB4q3HTgjgG9CBWuxGxZ0LnfRKCSgxT
            286v71A4TLO4wZJPZNpldy9Ej0gpNQrTgrClhXpToQyRAn+bQmqkvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-07T19:23:21Z"
    mac: ENC[AES256_GCM,data:NVZwWg+F5kaaVhh/UJiNhy/fIUsTJgzaGZU9LAM3mD4koMZsh/MRCS04D6cMdi5ji7IzUBt6o6pm60rq4mJPNvWpvzgYeCABjhIzDifmgppcop5xdBwrruM1oqOFHc+eLxnpTAN7VpO2Dtw8Xq/cwt4Gsmv7AxH20PhrC7SFMB4=,iv:M7KEoGqDKQE5cRGZsqL/k/Mz+koDNGzR1eHTnMkh020=,tag:7cUdRBHDAQwv2WrVMNSGCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
