id: whatsapp
url: http://bridge-whatsapp.synapse.svc.cluster.local:29318
as_token: _AS_
hs_token: _HS_
sender_localpart: Wd0rSz0Q42UzSqs53ZrL3G963XOSF0em
rate_limited: false
namespaces:
    users:
        - regex: ^@whatsappbot:samcday\.com$
          exclusive: true
        - regex: ^@whatsapp_[0-9]+:samcday\.com$
          exclusive: true
