# https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare
      key: token
logLevel: debug
policy: sync
provider: cloudflare
serviceMonitor:
  enabled: true
txtOwnerId: home-cluster
