# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

controller:
  extraContainers:
    - image: tailscale/tailscale:v1.33
      name: tailscale
      command:
        - /bin/sh
        - -c
        - |-
          tailscaled --state=kube:ingress-ts-auth-key --socket=/tmp/tailscaled.sock --tun=userspace-networking &
          PID=$!
          tailscale --socket=/tmp/tailscaled.sock up --login-server=https://samcday-headscale.fly.dev/ --authkey=$TS_AUTH_KEY --accept-dns=false
          wait $PID
      envFrom:
        - secretRef:
            name: services-tailscale-auth
      livenessProbe:
        exec:
          command:
            - tailscale
            - --socket=/tmp/tailscaled.sock
            - status
        initialDelaySeconds: 3
        periodSeconds: 5
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: '2'
          memory: 1Gi
  kind: Deployment
  metrics:
    enabled: true
  service:
    externalIPs: [100.64.0.8]
  terminationGracePeriodSeconds: 5
  updateStrategy:
    type: Recreate
