apiVersion: monitoring.coreos.com/v1alpha1 
kind: AlertmanagerConfig
metadata:
  name: dms
  namespace: monitoring
spec:
  receivers:
    - name: dms
      webhookConfigs:
        - urlSecret:
            name: dms-url
            key: url
  route:
    routes:
      - matchers:
          - name: alertname
            value: Watchdog
        receiver: dms
        groupWait: 0s
        repeatInterval: 30m
