apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terraform
  namespace: monitoring
spec:
  interval: 5m
  approvePlan: auto
  path: home-cluster/monitoring
  sourceRef:
    kind: GitRepository
    name: hominions
    namespace: flux-system
