---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  chart:
    spec:
      chart: syncthing
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 3.5.2
  install:
    remediation:
      retries: -1
  interval: 5m
  releaseName: syncthing
  upgrade:
    remediation:
      retries: -1
  values:
    # https://github.com/k8s-at-home/charts/blob/master/charts/stable/syncthing/values.yaml
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    controller:
      type: daemonset
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/home-cluster-data
        mountPath: /var/syncthing
    service:
      listen:
        enabled: false
      discovery:
        enabled: false
    tolerations:
      - key: samcday.com/cloud
        effect: NoExecute
