---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
      version: 1.6.1
  install:
    crds: Create
    remediation:
      retries: -1
  interval: 1h0m0s
  releaseName: flux
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: values
