---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: age-key
  interval: 1h
  path: ./kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  timeout: 5m
  wait: true
