---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: libreddit
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-system
  interval: 5m
  path: ./libreddit
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  timeout: 30s
  wait: true
