---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synapse
  namespace: flux-system
spec:
  interval: 5m
  path: ./synapse
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  timeout: 5m
