# https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/values.yaml
imageautomationcontroller:
  create: false
imagereflectorcontroller:
  create: false
prometheus:
  podMonitor:
    create: true
