---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      version: 3.1.0
  install:
    crds: CreateReplace
  interval: 1h
  releaseName: openebs
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: openebs-values
