# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
# extraInitContainers:
#   - name: init-litestream
#     image: litestream/litestream:0.3.9
#     args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/var/lib/grafana/grafana.db']
#     volumeMounts:
#       - name: litestream-config
#         mountPath: /etc/litestream.yml
#         subPath: litestream.yml
# extraContainerVolumes:
#   - name: litestream-config
#     configMap:
#       name: grafana-litestream
ingress:
  enabled: true
  ingressClassName: nginx
  hosts: [grafana.home.samcday.com]
persistence:
  enabled: true
  storageClassName: openebs-lvmpv
