---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: jellyfin-helm
        namespace: flux-system
  interval: 1h
  values:
    # https://github.com/samcday/jellyfin-helm/blob/main/values.yaml
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: [jellyfin.home.samcday.com]
      paths: [/]
    persistence:
      config:
        enabled: true
        storageClass: syncthing
      media:
        enabled: true
        existingClaim: media
