---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  chart:
    spec:
      chart: seaweedfs
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
      version: "3.45"
  interval: 5m
  values:
    # https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/values.yaml
    filer:
      data: &pvc
        type: persistentVolumeClaim
        size: 10G
        storageClass: openebs-hostpath
      logs: *pvc
    master:
      data: *pvc
      logs: *pvc
    s3:
      enabled: true
      logs: *pvc
    volume:
      replicas: 2
      nodeSelector: ""
      data: *pvc
      index: leveldb
      idx: *pvc
      logs: *pvc
