---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  chart:
    spec:
      chart: k8s/charts/seaweedfs
      sourceRef:
        kind: GitRepository
        name: samcday-seaweedfs
  interval: 5m
  values:
    # https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/values.yaml
    filer:
      data: &flr
        hostPathPrefix: /srv/home-cluster-data/seaweedfs-filer
      logs: *flr
    master:
      data: &mstr
        hostPathPrefix: /srv/home-cluster-data/seaweedfs-master
      logs: *mstr
    volume:
      replicas: 1
      nodeSelector: ""
      data: &vol
        hostPathPrefix: /srv/seaweedfs-volume
      index: leveldb
      idx: *vol
      logs: *vol
