---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: seaweedfs
spec:
  chart:
    spec:
      chart: k8s/charts/seaweedfs
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: samcday-seaweedfs
  interval: 5m
  values:
    # https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/values.yaml
    filer:
      data: &pvc
        type: persistentVolumeClaim
        size: 10Gi
        storageClass: syncthing
      encryptVolumeData: true
    global:
      monitoring:
        enabled: true
    master:
      data: *pvc
    volume:
      replicas: 1
      nodeSelector: ""
      data: &vol
        hostPathPrefix: /srv/seaweedfs-volume
      index: leveldb
      idx: *vol
      logs: *vol
      maxVolumes: 10
