apiVersion: v1
kind: Secret
metadata:
    name: dms-token
    namespace: kube-system
stringData:
    DMS_TOKEN: ENC[AES256_GCM,data:tdktvH+2tTGyQ0qE/epcrCbArKlQSg==,iv:QmV7LPStdNZWTCB3IRcQk20z7lauVmAwr1+Qm+ffUA4=,tag:Neh+HNBxfJe68EBZ0OikAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VEk2d1RlZjNkQkdlU0VI
            TSt5RmZJc24vTTBPcHM1cTFPM09iSHJESkc4CjNFckhLc09KKytyY2ZianVGNzBr
            MUExK3RVMDVXbm50NFhqT1dSc2Q3OFkKLS0tIGdKMXBRZWVjMURROXg1d2dQMjhG
            T1RWaXJocy9DR0kzOEVUaGFqNmtQZWsKOSKVtB9k3VmHnbpV/j5VaQUB5DNB6/it
            MbiviZzP3C13pah3Q5mW6jtIeYOu1xZAZOWN6dkNOA9atEsUByo9/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-11T16:27:52Z"
    mac: ENC[AES256_GCM,data:cqxr2BhiaDX6tiCuNLgBa9GaDp1SyZiGB2xlrFGTppvf7GVKJbDvjpCWcqkHnYgM4lK5AjGhj/nD2h9iL6hOGnev7D+TzdhWaYWvHflT8vRnR5xa0fzQVVpD4cOjWsnT+YyvWdseQdLEQm68yZHaiu6+MM8u/yNDfQjryMajS7w=,iv:Xp4r5qPFbWB0kckz/V1gpcHHmX8iPFc+ra9/gKmxY8c=,tag:Dy2ZuTTgpXMNcD28VxtPXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
