apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
    - token: ENC[AES256_GCM,data:GwYX6VHMeIxv0IuIpKI6ByWjQQR+Luw=,iv:J2DyECnHqMgDiDw2BGjm21pd5Gwd4iRjtS5mrVdF718=,tag:/utUrvN3RDBUBBnIN3APYw==,type:str]
      description: Best token
localAPIEndpoint:
    advertiseAddress: _TAILSCALE_IP_
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
    kubeletExtraArgs:
        volume-plugin-dir: /var/lib/kubelet/flex-volume-plugins/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T17:21:52Z"
    mac: ENC[AES256_GCM,data:5KqfFKqcZ+cHWdqmaaNNVhyfCyod2Jf5LGz9do88oPoCzsnd/3rpE6mMqV55/VKTN7fa6ISWMgQqVMNScyrh9dXmisY+cvwx/QIhVqUuv4h6DeJWb7B8PCJAW80wRYoMUKnyoKSwE71aXAQO+u0EKGCLMiczEkRCm3igeMKVIi8=,iv:TVZuyhM8JZ4qf/pii2ww3HY7pZ1MkzMfCnyuto6U4lk=,tag:11Q/I9tTtXl82z3poo/pBQ==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controllerManager:
    extraArgs:
        flex-volume-plugin-dir: /var/lib/kubelet/flex-volume-plugins/
networking:
    podSubnet: 10.42.0.0/16
    serviceSubnet: 10.43.0.0/16
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T17:21:52Z"
    mac: ENC[AES256_GCM,data:5KqfFKqcZ+cHWdqmaaNNVhyfCyod2Jf5LGz9do88oPoCzsnd/3rpE6mMqV55/VKTN7fa6ISWMgQqVMNScyrh9dXmisY+cvwx/QIhVqUuv4h6DeJWb7B8PCJAW80wRYoMUKnyoKSwE71aXAQO+u0EKGCLMiczEkRCm3igeMKVIi8=,iv:TVZuyhM8JZ4qf/pii2ww3HY7pZ1MkzMfCnyuto6U4lk=,tag:11Q/I9tTtXl82z3poo/pBQ==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
containerRuntimeEndpoint: /run/containerd/containerd.sock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T17:21:52Z"
    mac: ENC[AES256_GCM,data:5KqfFKqcZ+cHWdqmaaNNVhyfCyod2Jf5LGz9do88oPoCzsnd/3rpE6mMqV55/VKTN7fa6ISWMgQqVMNScyrh9dXmisY+cvwx/QIhVqUuv4h6DeJWb7B8PCJAW80wRYoMUKnyoKSwE71aXAQO+u0EKGCLMiczEkRCm3igeMKVIi8=,iv:TVZuyhM8JZ4qf/pii2ww3HY7pZ1MkzMfCnyuto6U4lk=,tag:11Q/I9tTtXl82z3poo/pBQ==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
