---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      version: v4.2.0
  install: &rem
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: csi-driver-nfs
  upgrade: *rem
  values:
    # https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/v4.2.0/csi-driver-nfs/values.yaml
    controller:
      runOnControlPlane: true
      replicas: 2
