apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k3s-s3-config
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: k3s-s3-config
  template:
    metadata:
      labels:
        app: k3s-s3-config
    spec:
      containers:
        - name: setup
          image: busybox:stable
          command:
            - /bin/sh
            - -c
            - |-
              set -uexo pipefail
              while true; do
                if ! diff /bucket/config.yaml /host/s3.yaml; then
                  cp /bucket/config.yaml /host/s3.yaml
                fi
                sleep 15
              done
          securityContext:
            privileged: true
          volumeMounts:
            - name: backups-bucket
              mountPath: /bucket
            - name: host
              mountPath: /host
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
      volumes:
        - name: backups-bucket
          secret:
            secretName: backups-bucket
        - name: host
          hostPath:
            type: DirectoryOrCreate
            path: /etc/rancher/k3s/config.yaml.d
