apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: hcloud-cloud-init
    files: [HCLOUD_CLOUD_INIT=hcloud-cloud-init.sh.base64]
  - name: vertical-pod-autoscaler-values
    files: [vertical-pod-autoscaler/values.yaml]
resources:
  - ../config
  - cert-manager.yaml
  # - cluster-autoscaler/cluster-autoscaler.yaml
  # - cluster-autoscaler/hcloud-provisioner.yaml
  - coredns.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - ip-masq-agent.yaml
  - postgres-operator.yaml
  - prometheus-operator.yaml
  - stc.yaml
  - tailscale-node-controller.yaml
  # - terraform.yaml
  # - vertical-pod-autoscaler/helm-release.yaml
  # - vpas.yaml
