---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      version: 3.5.0
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: openebs
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    # https://github.com/openebs/charts/blob/main/charts/openebs/values.yaml
    apiserver:
      tolerations: &toler
        - key: samcday.com/cloud
          effect: NoExecute
    localprovisioner:
      tolerations: *toler
    provisioner:
      tolerations: *toler
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
