---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      version: 3.3.1
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 5m
  releaseName: openebs
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: openebs-values
