apiVersion: v1
kind: Secret
metadata:
    name: admin-password
    namespace: miniflux
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:9Tzg6FXyggTWNv3Mrq5Fhp7o7gROmg5crrhVlo/nm70v4H+NaIWBCAxXHLUiIxA7fjcrfr3naBVDMqKuAp8Qbg==,iv:NMxSdTUds4PxIK0MYegeYOkzehRXsT7bhrQaz6L+uRg=,tag:yXtDbUERIGM+xyyY9a0s4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTArRkRrbVBjQVlUQUxM
            ZTFCUkVOVmVVMExhdUp4bjlld0lsbVhaS200ClZMS0RUZlh2V3IxS3hiLytRb2pu
            cG5sVDljb0kxWXRoN1YwblV2TG1mcWMKLS0tIEdHYVREN3VjZWpMNzdaUkpMR1Fm
            Ymx1Z3piUzBjcE9Bb2ptMDh4TW5FVG8KTtx0e2rnVAHtCmVWqir0fjb518aVTJnq
            gXQlUj47Tjp63I0TcdZ07cv+qm53xG3zxSbXY53muW9zNzHXJ+327w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-08T21:07:28Z"
    mac: ENC[AES256_GCM,data:i6++dGJvkiGVmza+cgfwbFuLtEb7XaNM2bFJ2zeBjCTCfI81SvCXlbrGfiaF952NGevTDSzqcjc2apu8d1MTV64dQEnRabsp672VU79y1uErwfuWBHeOqRnkTf7BCFtYTbM2VYKXP3kA+sRDVpgQmvEzl/tUmvbopegAFz73+h0=,iv:W71zzIMvdn0I7RtGVoGh2Syhe6I48+3R2rXvfJPaUxQ=,tag:QrxkuSyA3/EkRe1GDGXopA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
