# https://github.com/morremeyer/charts/blob/main/charts/generic/values.yaml

command:
  - /bin/ash
  - -c
  - |-
    set -ueo pipefail
    export DATABASE_URL=postgres://postgres:$DB_PASS@postgres-postgresql/miniflux?sslmode=disable
    exec /usr/bin/miniflux
env:
  ADMIN_USERNAME: admin
  BASE_URL: https://miniflux.home.samcday.com
  CREATE_ADMIN: "1"
  INVIDIOUS_INSTANCE: invidious.samcday.com
  METRICS_ALLOWED_NETWORKS: 0.0.0.0/0
  METRICS_COLLECTOR: "1"
  RUN_MIGRATIONS: "1"
envValueFrom:
  ADMIN_PASSWORD:
    secretKeyRef:
      name: admin-password
      key: ADMIN_PASSWORD
  DB_PASS:
    secretKeyRef:
      name: postgres-postgresql
      key: postgres-password
image:
  repository: miniflux/miniflux
  tag: 2.0.38
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  className: nginx
  hosts:
    - host: miniflux.home.samcday.com
      paths:
        - path: /
          servicePortName: http
  tls:
    - hosts: [miniflux.home.samcday.com]
      secretName: certificate
livenessProbe:
  httpGet:
    path: /healthcheck
ports:
  - name: http
    containerPort: 8080
readinessProbe: ~
replicaCount: 1
