# https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml

hubble:
  metrics:
    enabled:
      - drop
      - flow
      - http
      - icmp
      - tcp
    serviceMonitor:
      enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
