---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: age-key
  interval: 1m0s
  path: ./postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  timeout: 5m
