---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: suc-plans
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-system
  interval: 5m
  path: ./suc-plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  timeout: 1m
  wait: true
