---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: syncthing
  namespace: flux-system
spec:
  interval: 1h
  path: ./syncthing
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  wait: true
