# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [alertmanager.home.samcday.com]
    paths: [/]
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [grafana.home.samcday.com]
kubeControllerManager:
  serviceMonitor:
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeProxy:
  enabled: false
kubeScheduler:
  serviceMonitor:
    insecureSkipVerify: true
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [prometheus.home.samcday.com]
    paths: [/]
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: sam-laptop
      static_configs:
      - targets: [100.101.117.111:9100]
        labels:
          job: node-exporter
    enableAdminAPI: true
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 30d
    retentionSize: 30GB
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    walCompression: true
prometheus-node-exporter:
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    - --collector.textfile.directory=/var/lib/misc/vanilla-megabase/graftorio2
  prometheus:
    monitor:
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
        replacement: $1
        action: replace
