apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: factorio-server-charts
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: main
  secretRef:
    name: code-samcday-com
  url: https://code.samcday.com/samcday/home-cluster-media
