apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: dms
  namespace: kube-system
spec:
  inhibitRules:
    - equal: [namespace]
      sourceMatch:
        - name: alertname
          value: InfoInhibitor
      targetMatch:
        - name: severity
          value: info
  receivers:
    - name: dms
      webhookConfigs:
        - urlSecret:
            name: dms-url
            key: url
    - name: "null"
  route:
    receiver: "null"
    routes:
      - matchers:
          - name: alertname
            value: Watchdog
        receiver: dms
        group_wait: 0s
        repeat_interval: 10m
      - matchers:
          - name: alertname
            value: InfoInhibitor
        receiver: "null"
