apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
- name: grafana-litestream
  files: [grafana/values.yaml]
  options: {disableNameSuffixHash: true}
- name: grafana-values
  files: [grafana/values.yaml]
- name: promtail-values
  files: [promtail/values.yaml]
- name: kube-prometheus-stack-values
  files: [kube-prometheus-stack/values.yaml]
resources:
- ../config
- grafana/helm-release.yaml
# - loki/
- kube-prometheus-stack/helm-release.yaml
- namespace.yaml
# - promtail/helm-release.yaml
