apiVersion: v1
kind: Service
metadata:
  name: sam-laptop-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    release: kube-prometheus-stack
spec:
  type: ExternalName
  externalName: 100.101.117.111
  ports:
  - name: http-metrics
    port: 9100
