---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 41.3.1
  install:
    remediation:
      retries: -1
  interval: 1h
  releaseName: kube-prometheus-stack
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
    - kind: Secret
      name: dms-url
      valuesKey: url
      targetPath: alertmanager.config.receivers[0].webhook_configs[0].url
