# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [alertmanager.home.samcday.com]
    paths: [/]
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [grafana.home.samcday.com]
kubeControllerManager:
  serviceMonitor:
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeProxy:
  enabled: false
kubeScheduler:
  serviceMonitor:
    insecureSkipVerify: true
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [prometheus.home.samcday.com]
    paths: [/]
  prometheusSpec:
    enableAdminAPI: true
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 30d
    retentionSize: 30GB
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    walCompression: true
