---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
      version: 2.7.0
  install:
    crds: Create
    remediation:
      retries: -1
  interval: 5m
  releaseName: flux
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    # https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/values.yaml
    helmController: &gofast
      container:
        additionalargs:
          - --concurrent=10
      replicas: 2
      tolerations:
        - key: samcday.com/cloud
          effect: NoExecute
    imageAutomationController:
      create: false
    imageReflectorController:
      create: false
    kustomizeController: *gofast
    prometheus:
      podMonitor:
        create: true
    sourceController:
      tolerations:
        - key: samcday.com/cloud
          effect: NoExecute
