---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-flannel
  namespace: flux-system
spec:
  interval: 5m
  path: home-cluster/kube-flannel
  prune: true
  sourceRef:
    kind: GitRepository
    name: hominions
    namespace: flux-system
  timeout: 5m
