---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: libreddit
  namespace: flux-system
spec:
  interval: 5m
  path: ./libreddit
  prune: true
  sourceRef:
    kind: GitRepository
    name: hominions
  timeout: 30s
