---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      version: 0.14.0
  interval: 5m
  releaseName: tf-controller
  values:
    # https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml
    runner:
      serviceAccount:
        allowedNamespaces: [kube-system, monitoring]
    tolerations:
      - key: samcday.com/cloud
        operator: Exists
