apiVersion: v1
kind: Secret
metadata:
    name: mautrix-signal
    namespace: synapse
stringData:
    AS_TOKEN: ENC[AES256_GCM,data:yXlkutBsfJdYr9a+iOw2JYfFoxrSUX7I3xSsaVSbpY12+Des2jzEDi9rjTS+SrdGiaLGN0moEdrhF6P2c5Lktw==,iv:keHeqCvFkKUGzdOouRgXZV4KISyr/TldhOrI3iy36iE=,tag:2jiqK7VAcs3XtMrhwIWtzA==,type:str]
    HS_TOKEN: ENC[AES256_GCM,data:DEi+fvtF6rtg2TdnrLOM72HAD1jKaPNwMaI1c1UjYSt+Pf8TV5T7kt7k0KXAb5opAlZsA1Ke4EH+qjqhMi+KAg==,iv:HCv9+Bv8kwNCA7E8x9nN46VOjBIxdWkasxOUiBG5800=,tag:9E1oW/fy20iPpuxg81I3JA==,type:str]
    SHARED_SECRET: ENC[AES256_GCM,data:gxmL3Uw6Ngv+HY9doiwKpPI8U0KlwCMUzUSx2roRLnpdbSv8PbdxAwWum77DQCgm9rydaLz1GdsFtOvczdYrtA==,iv:OoppmPn3V6InZPX2/o01btJvrf0SYYizccXaRvf7lY0=,tag:CDSnBu5YZwB6ugQwu9RH2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRU9SMGk1MW9sYlFSMlhi
            OVhoRUFLWHNkMi9heFVNY3hLRElVSmpWYlM0CmJ1aTZxNFpaWXY1d1JkUklTc2k5
            SDMvRWQwenQ2RkRiek82dXdORnhtWmcKLS0tIEY3bnNBMVZscit2RlNBUU5DRFQw
            N2JnL01ZTlN2M0NRcHZLczF6UlBqbGMK7EfVjSaH7m94FlaSkEaZtJ3x+hoBX1mm
            TIFov72IRHUKKjWDdZcP3AgKe+EtN5ZeY+xBoLAlfmTngSAUJvgw6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-10T15:52:10Z"
    mac: ENC[AES256_GCM,data:WZgpd2t0M0ewxX7Tjdy8ykToDYPeMsjWMOaEW5fHRI4e9MufoRP1LImaHvI99dZG1CKIz2jI1Y/QLXxw0N/aHLwdz0T64b2KACXYjuZa7j7mH2taMdsg8SkHzbLCb6SDv0a/grCZ8XL3eYFOsK10JY6uXzZuYKGYx0mUhdZy/a0=,iv:+K+798MJQw+A1cJ5DxTobS2pmXoollN3BbEbFoNODS8=,tag:U0rlK510m1KHQJeek4V74Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
