apiVersion: v1
kind: Secret
metadata:
    name: synapse
    namespace: synapse
stringData:
    MACAROON_SECRET_KEY: ENC[AES256_GCM,data:GBJRQ8eO6yuKbCrT9eLtz6wWv3DtYTdDCcQiHjl1Wg5ioJgHR2K3N/T4h1ex/L4SC60=,iv:qbrgTbmJ9UNrH1LeBWhPezuiee2KioswBVkWW1kCxRI=,tag:RKGhOX17U38+CEo/qJU65A==,type:str]
    REGISTRATION_SECRET: ENC[AES256_GCM,data:kuOHtC5iCHo4tm3vSdBZEKOvg0rgXG1fYtcsqC4zCKd8htc9ugVUKQc6gCfAyRWQ0po5KUUczBol1F03vlg0LQ==,iv:8niE9+wa7a9s17Gmnfn8JPpaWMAgnSMHlXU8+4z4vWI=,tag:IVsOM8t/TURzJaocyi2I0A==,type:str]
    SIGNAL_SENDER_LOCALPART: ENC[AES256_GCM,data:gO6hhpM79XDpzX5/xI139AZzb/SYfLQbr2tfzfI2zgtj8yRRYqSWa8yC4q1RZBSSUxSYjvaGKA1Jw/S3JFxBqA==,iv:XtnAUWdz5IpsD3ceVZyL+oPJyT6dLeuZeVPRlkD+11A=,tag:QAJ3r6PUNUx1VA+uJMHGIQ==,type:str]
    WA_SENDER_LOCALPART: ENC[AES256_GCM,data:DVag1jaBsQ5QsWXiOVWdbV/WYSAKChUIVWZGUi6guYU=,iv:hnj230PboFkUXrHP86xjftx3LD6BJlxX91bGQlr7inM=,tag:AkisF1mQeGeUpkBa2zMPUQ==,type:str]
    TELE_SENDER_LOCALPART: ENC[AES256_GCM,data:WbNDrKbnCmo69rgCP4KF2GMpSz6DsepGOin0g6ZxSmoVClk7/bgiEIlcyA7xIqlZpCRVCVY/cw7Aiwe8OZtLlw==,iv:QIpj/sNy/yMJcJMvTdafrQqfv13+LRrXsnKb/G6QWEc=,tag:aozTLxKvXkjLKw31Pa1S2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkxaYWMzMXNKSEVLSVgv
            OHpBOHJFQWliT1hNa2VPL09naG9IYjB6dUI0CnArYVpndVFYKzdmUnAxQkVkODhV
            aFJ5U3J5c2NoQmJBM2J2UzV0NkU1eGMKLS0tIG9ZM3FjNnBxVTlWOVl3NGhPM0xB
            K0xCVXVCNXdjbjFydEx5ZnRGdTRTT1EKBab1xoVoWvwgraB1VhdxTkkh5D0HHm4t
            PJp4Q8rI6JXpHbA2pVq05pWLZTpjXjObU3hBrl6yz2AuCQs59STalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-10T15:52:10Z"
    mac: ENC[AES256_GCM,data:x93ZMpItba1ka3nKdrKvTjXCWNKesFqADuZuP2nIY5W/Lb+5WoKOGAgBV0Xm7lDCTM/+mTD1NwXNROm3ZiTueqri9kU2HvgZW8SV5N3/cS9MhbIrDY/jh/n/eEU4Jy5Co9k43UefBSpG1TCe/7dNVhgZOiFkp3xTodH7nmURGxo=,iv:wsM/yfVBTt3GEFPd5/HfnVwP693pEiLFFZ8adZDwCDg=,tag:yM2GX+sdDz4DOrs8DG4WcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
