apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local cluster.home.samcday.com in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        # Forward DNS queries through MagicDNS, which itself is configured with an appropriate fallback resolver.
        forward . 100.100.100.100:53
        cache 30
        loop
        reload
        loadbalance
    }
