# fip-controller Job is associating ip using netlink, but it's getting intermittently yeeted.
# dunno why. for now, hax!
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hack-fip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: hack-fip
  template:
    metadata:
      labels:
        app: hack-fip
    spec:
      containers:
        - name: setup
          image: busybox:stable
          command:
            - /bin/chroot
            - /host
            - /bin/bash
            - -c
            - |-
              set -uexo pipefail
              while true; do
                ip addr replace 49.12.115.117 dev eth0
                sleep 15
              done
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host
              mountPath: /host
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/home-fip: 49.12.115.117
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
      volumes:
        - name: host
          hostPath:
            type: Directory
            path: /
