apiVersion: v1
kind: Secret
metadata:
    name: hcloud-token
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:phZW6MGcCWN6kTpkpEDv83xsy/wsDC+/8hOGMlwl1Feb+1ldPk2mwWczjk1J+QtGG+udkjJMoIqT/D4ujbVfhQ==,iv:fn5VrIPYKNXDJnao4cDNO3LwaEjqTJabQLK5LI9r+Qw=,tag:WnTPfvwt5iAwhKjBEfEn6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudUszVDBpUkgyL3R4ZTNw
            YXRrTThJUktvMXdEcDlrRkZKbUdKdmIyL1ZZCjNTTU5nOWk4Mi83azNLdmpFTERN
            bkV3WWNIUU1IS0J3TnJMUFdqaEozODgKLS0tIDVwcCtnYXFKOXRBY2wxc1hZbU9H
            M1h3ZGxjR3dlYjFGRERobEN4aUJEdVkKSM7DyS+zx79tcz1z6kCW666tK6oazmk1
            V7O3AjhAdBM+20ElFcgAcuQKz11n8bXhzRAgz8lDG+kpckgRpB1OCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T11:34:45Z"
    mac: ENC[AES256_GCM,data:qVIbSH6hNyHKuW6OWzatOjdsZujCmK3UFYGWTwa7cs/YnI9ofBz0WkCAqQsQbVhdYMvqRfdIzgY2aX+Ty+NWRTmWA/cAOYIhIHH+Y7xN5SsmsB5cVaFiJnUHrFDNnZ7diTirgg2PBT/xgC8RQgiB6B+3QdVd7Y687SurRAnTn60=,iv:SMsr1C3e7BUDLuqMb1wkxn2ItIJEqlxzu9yXXda2Xh8=,tag:KrKRxzDGaQzCPNm2p/0lAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
