apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: cert-manager-values
    files: [cert-manager/values.yaml]
  - name: cilium-values
    files:
      - cilium/values.yaml
      - cilium/values-monitoring.yaml
  - name: external-dns-values
    files: [external-dns/values.yaml]
  - name: hcloud-cloud-init
    files: [HCLOUD_CLOUD_INIT=hcloud-cloud-init.sh.base64]
  - name: ingress-nginx-values
    files: [ingress-nginx/values.yaml]
  - name: openebs-values
    files: [openebs/values.yaml]
  - name: public-ingress-nginx-values
    files: [public-ingress-nginx/values.yaml]
  - name: prometheus-operator-values
    files: [prometheus-operator/values.yaml]
  - name: terraform-config
    files: [terraform/.terraform.lock.hcl, terraform/main.tf]
secretGenerator:
  - name: k3s-config
    files: [k3s-agent.yaml, k3s-server.yaml]
    options: {disableNameSuffixHash: true}
resources:
  - ../config
  - cert-manager/helm-release.yaml
  - cert-manager/issuers.yaml
  - cilium/helm-release.yaml
  - cluster-autoscaler/cluster-autoscaler.yaml
  - cluster-autoscaler/hcloud-provisioner.yaml
  - external-dns/helm-release.yaml
  - ingress-nginx/helm-release.yaml
  - openebs/helm-release.yaml
  - openebs/storageclass.yaml
  - public-ingress-nginx/helm-release.yaml
  - prometheus-operator/helm-release.yaml
  - suc-plans.yaml
  - terraform/apply-cronjob.yaml
  - terraform/state-pvc.yaml

  - github.com/rancher/system-upgrade-controller?ref=v0.9.1
