apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
    namespace: kube-system
spec:
    secretTemplates:
        - name: cloudflare
          stringData:
            token: ENC[AES256_GCM,data:S6CLQE2VIAuhDbaaGmuLal53e1QyjDyDJhan4KDeb5MNxJrWpIO+/w==,iv:fmKfrKA4MlaM4IQ7cOPhkHqmobmQnefk2/JUCOF/ej8=,tag:ovsKWDcsFvtzwyjQxCb6Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOTVUTEltRUs4eGVMdlR0
            K0lXd1VwR2l6NzBJenkrVjhFOWlCbXRDQjBRCm1mUnpXMEN4L08rRHN1OHRiOGpZ
            SXRtTW5GSGdPQ3hxZVBEbjhGYlpzNzQKLS0tIDRYUjlUcXRUT3JCMDNiZHJnUUto
            bDlDSXdhd1Eva0gzM0Fvc0s3NStJTHMKZlU6tgfcUtFd7v/15UcjnNeBd344W2U5
            HXEp/gElLIP3jyGkj95YQfbvCtZJK1UJ42NRk42zyXaW4joOE14FOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-14T16:55:56Z"
    mac: ENC[AES256_GCM,data:GPzeDpxTPF0mdLMWlL0/i8VPEbDVNnoxNTFs/xxVxyy7br3XJwDJlQXB1bu2q/8Q7dUOksvH0lpg7VlVtiaWF4U8+o6H6XuE8I3w6JXLlcu4eCCqHldvWFOP6hwAeUfWicdtcYyUYlQGshEFZ0t/1ysPINGBohWs+I6EG6ghzUQ=,iv:h26/wPr1FiMlH3YB1FL2E2k4UZ0SpONDwl8FOam7nfY=,tag:NRQmTHuX+i8U96bQpPcH8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
