---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vpas
  namespace: kube-system
spec:
  interval: 5m
  path: ./kube-system/vpas
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: vpas
  timeout: 5m
