---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vanilla-megabase
  namespace: factorio
spec:
  chart:
    spec:
      chart: charts/factorio-server-charts
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: factorio-server-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 5m
  postRenderers:
    - kustomize:
        patchesJson6902:
          # No need to run on the hostnetwork.
          # TODO: stop being lazy and fix this in fork.
          - patch:
              - op: replace
                path: /spec/template/spec/hostNetwork
                value: false
            target:
              group: apps
              version: v1
              kind: Deployment
              name: vanilla-megabase
  releaseName: vanilla-megabase
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: vanilla-megabase-values
    - kind: Secret
      name: token
      valuesKey: token
      targetPath: server_settings.token
