# https://github.com/SQLJames/factorio-server-charts/blob/main/charts/factorio-server-charts/values.yaml

factorioServer:
  save_name: 2021megabae
  update_mods_on_start: true
fullnameOverride: vanilla-megabase
image:
  tag: 1.1.69
mods:
  enabled: true
  portal:
  - helmod
  - ModuleInserter
  - VehicleSnap
persistence:
  enabled: true
  storageClassName: openebs-lvmpv
rcon:
  external: false
server_settings:
  name: samcday's (mostly) vanilla megabase project
  visibility:
    public: false
  username: samcday
  require_user_verification: true
  autosave_slots: 144 # (24 hours of 10min interval)
  auto_pause: false
  non_blocking_saving: true
service:
  type: ClusterIP
