# https://github.com/SQLJames/factorio-server-charts/blob/main/charts/factorio-server-charts/values.yaml

additionalVolumes:
  - name: host-script-output
    hostPath:
      path: /var/lib/misc/vanilla-megabase/
      type: DirectoryOrCreate
additionalVolumeMounts:
  - name: host-script-output
    mountPath: /factorio/script-output/
factorioServer:
  generate_new_save: false
  save_name: 2021megabae
fullnameOverride: vanilla-megabase
image:
  tag: 1.1.69
mods:
  enabled: true
  portal:
  - flib
  - graftorio2
  - helmod
  - ModuleInserter
  - VehicleSnap
persistence:
  enabled: true
  dataDir:
    # 144 autosave slots, factory as of 08/10 is 40mb.
    Size: 10Gi
  storageClassName: openebs-lvmpv
rcon:
  external: false
server_settings:
  name: samcday's (mostly) vanilla megabase project
  visibility:
    public: false
  username: samcday
  require_user_verification: true
  autosave_slots: 144 # (24 hours of 10min interval)
  auto_pause: false
  non_blocking_saving: true
service:
  type: ClusterIP
