apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 1h
  approvePlan: auto
  path: home-cluster/flux-system
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: tf-env
  sourceRef:
    kind: GitRepository
    name: hominions
    namespace: flux-system
