apiVersion: batch/v1
kind: CronJob
metadata:
  name: terraform-apply
  namespace: kube-system
spec:
  schedule: '@hourly'
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: init
              image: clowa/terraform:1.4.2
              args: [init]
              envFrom: &env
                - secretRef:
                    name: backblaze-key
                - secretRef:
                    name: dms-token
                - secretRef:
                    name: github-token
              volumeMounts: &volmounts
                - name: config
                  mountPath: /tf
          containers:
            - name: apply
              image: clowa/terraform:1.4.2
              args: [apply, "-auto-approve"]
              envFrom: *env
              volumeMounts: *volmounts
              workingDir: /tf
          restartPolicy: OnFailure
          serviceAccountName: terraform-apply
          volumes:
            - name: config
              configMap:
                name: terraform-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-apply
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-apply
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: ["*"]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: ["*"]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: ["*"]
- apiGroups: [notification.toolkit.fluxcd.io]
  resources: [receivers]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-apply
subjects:
- kind: ServiceAccount
  name: terraform-apply
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: terraform-apply
  apiGroup: rbac.authorization.k8s.io
