apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state
  namespace: kube-system
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
