# https://github.com/juanfont/headscale/blob/main/config-example.yaml
derp:
  urls: [https://controlplane.tailscale.com/derpmap/default]
  auto_update_enabled: true
  update_frequency: 24h
# Image updates should be picked up by renovate.
disable_check_updates: true
dns_config:
  nameservers:
    # TODO: setup a Pi-Hole/dnsmasq/something, use it here instead of Cloudflare DNS.
    - 1.1.1.1
  # split-dns - forward queries for domains to specific nameservers.
  restricted_nameservers:
    cluster.home.samcday.com: [10.43.0.10]
    internal: [fdaa:0:b5a8::3]
  # search domains injected into clients that `tailscale up --accept-dns`
  domains:
    - cluster.home.samcday.com
  magic_dns: true
  base_domain: tailnet.samcday.com
ephemeral_node_inactivity_timeout: 5m
# not exposed by Fly.io publicly, accessed via 6pn that is routed in Tailnet, so "insecure" here is probs ok for now.
grpc_allow_insecure: true
grpc_listen_addr: 0.0.0.0:50443
metrics_listen_addr: 0.0.0.0:9090
listen_addr: 0.0.0.0:8080
node_update_check_interval: 10s
private_key_path: /data/private.key
noise:
  private_key_path: /data/noise_private.key
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
db_type: sqlite3
db_path: /data/db.sqlite
acl_policy_path: /opt/acls.yaml
unix_socket: /var/run/headscale.sock
unix_socket_permission: "0770"
