---
derp:
  urls: [https://controlplane.tailscale.com/derpmap/default]
  auto_update_enabled: true
  update_frequency: 24h
# Image updates should be picked up by renovate.
disable_check_updates: true
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 0.0.0.0:50443
private_key_path: /data/private.key
noise:
  private_key_path: /data/noise_private.key
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s
db_type: sqlite3
db_path: /data/db.sqlite
acl_policy_path: /opt/acls.yaml
dns_config:
  nameservers:
    - 1.1.1.1
  # restricted_nameservers:
  #   cluster.home.samcday.com: [10.43.0.10]
  # domains: [cluster.home.samcday.com]
  magic_dns: true
  base_domain: tailnet.samcday.com
unix_socket: /var/run/headscale.sock
unix_socket_permission: "0770"
