apiVersion: v1
kind: Secret
metadata:
    name: mailgun
    namespace: mastodon
stringData:
    login: ENC[AES256_GCM,data:EmvHslUvg/k0FWmF06WLm9odW++lxDPItMKRxsJ7GQ==,iv:uy2VunOIHYgRJMBgTK01D7WkL/fijqqYLHNHn1Ku1Ts=,tag:T/1w0Mbyn287Hv/L1aSKsQ==,type:str]
    password: ENC[AES256_GCM,data:QdUEZHXpm0xSiw59HjFd4zNq+yP3rwhG2m1D8CH6F9Syz0n9awjQeGxjRZfTfSn6iA0=,iv:9wmRSlRaVTp+6uFZK0U+KFkAFx4j7JpIvw4yQKaRHbE=,tag:HbIwyIBavIactGYySCE9dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubHhSNXgrcHdWM1FZNVp6
            eU1zNVQ5U2liU3hvS2ZUbHdUMllNTFNoUTFrCkJhcUF3QlFIS3FkNkZjV0FnaG0z
            R2ZWMG9yd3YrYXlWY01RMEdDNHpBaEkKLS0tIDdUaUR4NU4yK24wSjU2WkV3aXk5
            ZmhINndYUjVFd3pIanRWUnhadVVGaXcKZU7j2VKaQP/ULuNraXcRMkKMpNx3IFp1
            9QZU+Fss0TrJ5qbmQBfZr82D86ioWFm5DCpxIDZZWAevc6fb1ws3CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T10:15:06Z"
    mac: ENC[AES256_GCM,data:T+cxcW0rdMkM07Nj6q/yMMnsC9+TrgpAqxkbNKeflczUEvdYC2lN4gwfg+fb+qY4OVhIWsAk6uZyQqLBwl8k1AMQdIQvGmwf2YqFF84Mhqj7T3TgG7IRsfBG9+rGkarmODot/7Z42R/ekuNG9smY7TGlb3NBQU1pLuRM6bMMZ1c=,iv:y+E5RsmFBhK2QtaS9m/tje8nS+BVsLOMbTBlyfPOFNg=,tag:gA8Rl4O3ffZ00OC82FjpzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
