apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: mastodon
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:qeVZyMFlo6wRq7X6JKfJdlh75k5IDAMXmcbjpQZxIj4=,iv:riMI+//9qCxyIHfDkB+wFQRHEHJ+dGXea4plVIkvpHk=,tag:1n5aKhxYBvHAtMUnYfOKxg==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:77Ddh98gnjY8eoBDunL2m1plFv0MThKlRKTqUUoQy/c=,iv:/WPnv3TqkPGxZuAUvzqzKWzqX+0l2f3NHYBWUp7u7ug=,tag:GUd1AXywxeBqgtKk5lfG0Q==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:91qPUisB37Hl6rsPsf2UCd9m4E9BHvaU8u9xFlJVAOw=,iv:N2K0TX1aWHobKgZ5ipdgPOF7xaujqmBMabux13IKQ80=,tag:GjdcmDrK2iioRUJk5HqvNw==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:KIAo9+QOuHnpMzk2ry4kxoJzw6yj+wkZwDanjWmaAZ8=,iv:wsCDVCvg7343fB1AtZyNADmVaofZ+VvMXCObqp3Ke3g=,tag:xrnA2TLVu/nZtX2zWIngyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubHhSNXgrcHdWM1FZNVp6
            eU1zNVQ5U2liU3hvS2ZUbHdUMllNTFNoUTFrCkJhcUF3QlFIS3FkNkZjV0FnaG0z
            R2ZWMG9yd3YrYXlWY01RMEdDNHpBaEkKLS0tIDdUaUR4NU4yK24wSjU2WkV3aXk5
            ZmhINndYUjVFd3pIanRWUnhadVVGaXcKZU7j2VKaQP/ULuNraXcRMkKMpNx3IFp1
            9QZU+Fss0TrJ5qbmQBfZr82D86ioWFm5DCpxIDZZWAevc6fb1ws3CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T13:59:22Z"
    mac: ENC[AES256_GCM,data:jSOgpeBevC53JNNq3VVzNjUZtqbhuwA1xuY66C/tyBg3HmgTsvzZ3vluRFbM0397Sk2ajd7qqi/yZFhhU31DtLfgQnS4/Ba0H/EC5GywaiqC6em3YJTgd0w6w1D4bRGuc6uu1h3zuNKmGnlxUNls5VTO+/PAd6qTmWufumSXB6Y=,iv:O5uAtzeIrJteYNRdhPzN0eYfCtMnWlCXfeuNBYVW0XU=,tag:7ta0CezJnZUpIKVfvf395w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
