apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
    - token: ENC[AES256_GCM,data:GwYX6VHMeIxv0IuIpKI6ByWjQQR+Luw=,iv:J2DyECnHqMgDiDw2BGjm21pd5Gwd4iRjtS5mrVdF718=,tag:/utUrvN3RDBUBBnIN3APYw==,type:str]
      description: Best token
localAPIEndpoint:
    advertiseAddress: 100.100.0.10
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T14:03:21Z"
    mac: ENC[AES256_GCM,data:4039hUHUH1GCeq6Hbos70yk7b6R5T9h/VMXBbPddI3piHLR8428QIqPfX11iZqNDp/tEOkTfV0qPQ48OM/w+i0YJnimiS9KktenQh2294ksQ8JNiceCmqoA4bh5QaMYMpNDHXENLHuZSwOf8oG1Muf9MfPTfNLs1EaQgSmW7JYc=,iv:Wh6s5/25mFC/TwaugxR9t8vZwUEkTFvmAvBakArtWd0=,tag:/77InfRkCu6bD+VPDi38lA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
containerRuntimeEndpoint: /run/containerd/containerd.sock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T14:03:21Z"
    mac: ENC[AES256_GCM,data:4039hUHUH1GCeq6Hbos70yk7b6R5T9h/VMXBbPddI3piHLR8428QIqPfX11iZqNDp/tEOkTfV0qPQ48OM/w+i0YJnimiS9KktenQh2294ksQ8JNiceCmqoA4bh5QaMYMpNDHXENLHuZSwOf8oG1Muf9MfPTfNLs1EaQgSmW7JYc=,iv:Wh6s5/25mFC/TwaugxR9t8vZwUEkTFvmAvBakArtWd0=,tag:/77InfRkCu6bD+VPDi38lA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
