apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
    - token: ENC[AES256_GCM,data:GwYX6VHMeIxv0IuIpKI6ByWjQQR+Luw=,iv:J2DyECnHqMgDiDw2BGjm21pd5Gwd4iRjtS5mrVdF718=,tag:/utUrvN3RDBUBBnIN3APYw==,type:str]
      description: Best token
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
    kubeletExtraArgs:
        volume-plugin-dir: /var/lib/kubelet/flex-volume
    taints: []
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T08:51:14Z"
    mac: ENC[AES256_GCM,data:xHQ65uN4+GjElZaTAgkcqvscpwbwGo1ovK3hCBFIWiUY9dRStiPag1/F5yrD8HV8S0+AKKuYOlBnp01jySicdIOGdWXCtazCAnA7vq+6//cAgGwsq5eX5gj7vqU4/pJGw3IeDBhpaeMnvKu1G75WGu75zvkZUucYawFgD1X1ejc=,iv:Ykl2zP611j8Me8naYWlQei2zQA4bss2lF1OYyyV11EY=,tag:tPjCOpxg6dMgaWr7Z1i1mA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controllerManager:
    extraArgs:
        flex-volume-plugin-dir: /var/lib/kubelet/flex-volume
networking:
    serviceSubnet: 10.43.0.0/16
    podSubnet: 10.42.0.0/16
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T08:51:14Z"
    mac: ENC[AES256_GCM,data:xHQ65uN4+GjElZaTAgkcqvscpwbwGo1ovK3hCBFIWiUY9dRStiPag1/F5yrD8HV8S0+AKKuYOlBnp01jySicdIOGdWXCtazCAnA7vq+6//cAgGwsq5eX5gj7vqU4/pJGw3IeDBhpaeMnvKu1G75WGu75zvkZUucYawFgD1X1ejc=,iv:Ykl2zP611j8Me8naYWlQei2zQA4bss2lF1OYyyV11EY=,tag:tPjCOpxg6dMgaWr7Z1i1mA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
containerRuntimeEndpoint: /run/containerd/containerd.sock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T08:51:14Z"
    mac: ENC[AES256_GCM,data:xHQ65uN4+GjElZaTAgkcqvscpwbwGo1ovK3hCBFIWiUY9dRStiPag1/F5yrD8HV8S0+AKKuYOlBnp01jySicdIOGdWXCtazCAnA7vq+6//cAgGwsq5eX5gj7vqU4/pJGw3IeDBhpaeMnvKu1G75WGu75zvkZUucYawFgD1X1ejc=,iv:Ykl2zP611j8Me8naYWlQei2zQA4bss2lF1OYyyV11EY=,tag:tPjCOpxg6dMgaWr7Z1i1mA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
