apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
    - token: ENC[AES256_GCM,data:GwYX6VHMeIxv0IuIpKI6ByWjQQR+Luw=,iv:J2DyECnHqMgDiDw2BGjm21pd5Gwd4iRjtS5mrVdF718=,tag:/utUrvN3RDBUBBnIN3APYw==,type:str]
      description: Best token
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
    kubeletExtraArgs:
        volume-plugin-dir: /var/lib/kubelet/flex-volume
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T19:50:43Z"
    mac: ENC[AES256_GCM,data:BT1DfoYjVk92xw5O8vJgQj8Ix7xCRgfmUhYM/OtknMOmBsVg3DtoL3bg07M6MmixIzZhKqaZyWao1zpKfvS8cYRP1RGld1Ry5k6++px4RoSaMCgba1V8IfDvPILy3PmzUTwTmqpOM4uhU6qYfK0etfvCu92ucCH8lAGtiQgKqDM=,iv:9X++7iXiroKbMWWPwUS/Duc/1SK9y/fVd6aQdfSZ6rc=,tag:L+U06st1dp5CSQvikvhyhA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controllerManager:
    extraArgs:
        flex-volume-plugin-dir: /var/lib/kubelet/flex-volume
networking:
    serviceSubnet: 10.43.0.0/16
    podSubnet: 10.42.0.0/16
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T19:50:43Z"
    mac: ENC[AES256_GCM,data:BT1DfoYjVk92xw5O8vJgQj8Ix7xCRgfmUhYM/OtknMOmBsVg3DtoL3bg07M6MmixIzZhKqaZyWao1zpKfvS8cYRP1RGld1Ry5k6++px4RoSaMCgba1V8IfDvPILy3PmzUTwTmqpOM4uhU6qYfK0etfvCu92ucCH8lAGtiQgKqDM=,iv:9X++7iXiroKbMWWPwUS/Duc/1SK9y/fVd6aQdfSZ6rc=,tag:L+U06st1dp5CSQvikvhyhA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
containerRuntimeEndpoint: /run/containerd/containerd.sock
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVnZYUm9Xb0Z1V21ja2FS
            c2ZmMkpJZ1FKclJqYzhUam44NDNaYng5bWwwCkgwdTFXSE5jdGlCbFd6WEt0V0Nw
            cVpFSzFmcE9hLzZjN3JaME9aM2hjekUKLS0tIG5NbDNIdnNzK25vTHpVNmhaWGZZ
            VWJzblovNVZtczNQVm85M2sxd2NtUWcKOEMAU8GpCi1hmsUmLEIwAVMnS0w5eCIJ
            Axl6/T5B28PAagpysafYufvDcL3FUfZUkb1D29VCDnBpJG1lBW6AvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-15T19:50:43Z"
    mac: ENC[AES256_GCM,data:BT1DfoYjVk92xw5O8vJgQj8Ix7xCRgfmUhYM/OtknMOmBsVg3DtoL3bg07M6MmixIzZhKqaZyWao1zpKfvS8cYRP1RGld1Ry5k6++px4RoSaMCgba1V8IfDvPILy3PmzUTwTmqpOM4uhU6qYfK0etfvCu92ucCH8lAGtiQgKqDM=,iv:9X++7iXiroKbMWWPwUS/Duc/1SK9y/fVd6aQdfSZ6rc=,tag:L+U06st1dp5CSQvikvhyhA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.7.3
