---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vanilla-megabase
  namespace: factorio
spec:
  chart:
    spec:
      chart: charts/factorio-server-charts
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: factorio-server-charts
        namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 1h
  releaseName: vanilla-megabase
  upgrade:
    remediation:
      retries: -1
  values:
    # https://github.com/samcday/factorio-server-charts/blob/main/charts/factorio-server-charts/values.yaml
    account:
      accountSecret: account
    additionalContainers:
      - name: caddy-scriptoutput
        image: caddy:2-alpine
        ports:
          - name: scriptoutput
            containerPort: 8123
        volumeMounts:
          - name: caddyfile
            mountPath: /etc/caddy/Caddyfile
            subPath: Caddyfile
          - name: datadir
            mountPath: /usr/share/caddy
    additionalVolumes:
      - name: caddyfile
        configMap:
          name: vanilla-megabase-caddyfile
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: samcday.com/cloud
                operator: Exists
    factorioServer:
      generate_new_save: false
      save_name: 2021megabae
      update_mods_on_start: true
    fullnameOverride: vanilla-megabase
    image:
      tag: 1.1.80
    mods:
      enabled: true
      portal:
        - auto-research
        - flib
        - graftorio2
        - helmod
        - ModuleInserter
        - VehicleSnap
    nodeSelector:
        kubernetes.io/arch: amd64
    persistence:
      enabled: true
      storageClassName: syncthing
    rcon:
      external: false
    replicaCount: 0
    resources:
      requests:
        cpu: '1'
        memory: 1Gi
    server_settings:
      name: samcday's (mostly) vanilla megabase project
      visibility:
        public: false
      username: samcday
      require_user_verification: true
      autosave_slots: 144 # (24 hours of 10min interval)
      auto_pause: false
      non_blocking_saving: true
    service:
      type: NodePort
      port: 34197
      nodePort: 34197
      annotations:
        external-dns.alpha.kubernetes.io/hostname: factorio.samcday.com
    tolerations:
      - key: samcday.com/cloud
        effect: NoExecute
