---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.5.1
  install:
    remediation:
      retries: -1
  interval: 5m
  releaseName: promtail
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: promtail-values
