---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: jellyfin-helm
        namespace: flux-system
  interval: 1h
  releaseName: jellyfin
  valuesFrom:
  - kind: ConfigMap
    name: jellyfin-values
