---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.12.2
  install:
    crds: Create
    remediation:
      retries: -1
  interval: 5m
  postRenderers:
    - kustomize:
        patchesJson6902:
          # Ensure cilium agent uses Tailnet DNS exclusively, important for bootstrapping so it can always find control plane.
          - patch:
              - op: replace
                path: /spec/template/spec/dnsConfig
                value:
                  nameservers:
                    - 100.100.100.100
            target:
              group: apps
              version: v1
              kind: DaemonSet
              name: cilium
  releaseName: cilium
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
  - kind: ConfigMap
    name: cilium-values
    valuesKey: values-monitoring.yaml
