---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.12.2
  install:
    crds: Create
    remediation:
      retries: -1
  interval: 5m
  releaseName: cilium
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
  - kind: ConfigMap
    name: cilium-values
    valuesKey: values-monitoring.yaml
