# https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml

dnsPolicy: None
hostFirewall:
  enabled: true
hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
ipam:
  mode: kubernetes
ipv6:
  enabled: true
ipv4NativeRoutingCIDR: 10.42.0.0/16
ipv6NativeRoutingCIDR: fda1:cebd:8920::/48
k8sServiceHost: hominion.hominion.tailnet.samcday.com
k8sServicePort: 6443
# k3s default is to put pods in 10.42.0.0/16 and services in 10.43.0.0/16
kubeProxyReplacement: strict
loadBalancer:
  serviceTopology: true
operator:
  dnsPolicy: None
  rollOutPods: true
  replicas: 1
tunnel: disabled
