# https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml

hostFirewall:
  enabled: true
hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
ipam:
  mode: kubernetes
k8sServiceHost: hominion
k8sServicePort: 6443
# k3s default is to put pods in 10.42.0.0/16 and services in 10.43.0.0/16
ipv4NativeRoutingCIDR: 10.42.0.0/15
kubeProxyReplacement: strict
operator:
  rollOutPods: true
  replicas: 1
tunnel: disabled
