---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: miniflux
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 11.9.10
  install:
    remediation:
      retries: -1
  interval: 5m
  releaseName: postgres
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: postgres-values
