# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

controller:
  admissionWebhooks:
    # covered by main ingress controller I think?
    enabled: false
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - ingress-nginx
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - public-ingress-nginx
            - key: app.kubernetes.io/component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
  electionID: public-ingress-controller-leader
  hostPort:
    enabled: true
  ingressClass: public-nginx
  ingressClassResource:
    name: public-nginx
    controllerValue: k8s.io/public-ingress-nginx
  kind: Deployment
  metrics:
    enabled: true
  nodeSelector:
    samcday.com/hcloud: ""
  replicaCount: 2
  service:
    enabled: false
  tolerations:
    - key: samcday.com/hcloud
      operator: Exists
  updateStrategy: Recreate
