# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

controller:
  hostPort:
    enabled: true
  ingressClass: public-nginx
  ingressClassResource:
    name: public-nginx
    controllerValue: "k8s.io/public-ingress-nginx"
  kind: DaemonSet
  nodeSelector:
    samcday.com/hcloud: ""
  service:
    enabled: false
  tolerations:
    - key: samcday.com/hcloud
      operator: Exists
