# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

controller:
  extraContainers:
    - image: cloudflare/cloudflared:1357-ec2d18ea4fbe
      name: cloudflared
      args:
      - tunnel
      - --no-autoupdate
      - run
      - --no-tls-verify
      - --url
      - https://localhost
      envFrom:
        - secretRef:
            name: cloudflared-tunnel-token
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: '2'
          memory: 1Gi
  kind: Deployment
  metrics:
    enabled: true
  service:
    enabled: false
  terminationGracePeriodSeconds: 5
  tolerations:
    - key: samcday.com/oci
      operator: Exists
      effect: NoExecute
  updateStrategy:
    type: Recreate
