---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: libreddit
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: morremeyer
        namespace: flux-system
      version: 5.3.1
  interval: 5m
  releaseName: libreddit
  values:
    # https://github.com/morremeyer/charts/blob/main/charts/generic/values.yaml
    env:
    image:
      repository: libreddit/libreddit
      tag: arm
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: nginx
      hosts:
      - host: libreddit.samcday.com
        paths:
          - path: /
      tls:
        - hosts: [libreddit.samcday.com]
          secretName: certificate
    livenessProbe:
      httpGet:
        path: /settings
    ports:
      - name: http
        containerPort: 8080
    readinessProbe: ~
    replicaCount: 1
