apiVersion: v1
kind: Secret
metadata:
    name: bridge-whatsapp
    namespace: synapse
stringData:
    WA_AS_TOKEN: ENC[AES256_GCM,data:AR3eiCMEmW8LZu9wA83W3K3dEQHn1BdeykUgJ4E4duOJNRpkruYZsAO2Qm7vQqBs9IMXWgf/S9p44yDqJhX4ww==,iv:X/q+1WiYkJqjfo84JxxDJ/UyXVrczWBWmgaUo4OTajI=,tag:ujSGn9fUwAYKy2qJxtmPMA==,type:str]
    WA_HS_TOKEN: ENC[AES256_GCM,data:4f87BBpq/EIwucMJopudAHzWZEOCGw09xl2qFeNuXca4+A+I6keE0ky5s04CjIMZBMT0DR/2V22lLZOXOvQbiQ==,iv:kuEXo2hIU9QuR2EpUEKtB2UfNr+I970dm0wm0EeW7j0=,tag:r2GYD1EX8Fq1X7/uVFE+Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkxaYWMzMXNKSEVLSVgv
            OHpBOHJFQWliT1hNa2VPL09naG9IYjB6dUI0CnArYVpndVFYKzdmUnAxQkVkODhV
            aFJ5U3J5c2NoQmJBM2J2UzV0NkU1eGMKLS0tIG9ZM3FjNnBxVTlWOVl3NGhPM0xB
            K0xCVXVCNXdjbjFydEx5ZnRGdTRTT1EKBab1xoVoWvwgraB1VhdxTkkh5D0HHm4t
            PJp4Q8rI6JXpHbA2pVq05pWLZTpjXjObU3hBrl6yz2AuCQs59STalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T19:15:23Z"
    mac: ENC[AES256_GCM,data:+pwwHYrjXOBEjHfGg9IYWVtIZrZkw6eVNxNDTzV+jUTTIy6wE95mBtz60bYvPJI5DAjFJ58qivc/cHg6Gbc1/VSovb59dBs7yB3a4du8rcdrWgo83raQCm4GE+xFDt1RcR2NNgpb+uCxpHsT3hmyH7xA6FicMPBmVp9wUfnUgE4=,iv:9d7YM6g5gXn5le8tc0tebHifzdZ8nrT5iaLCI6auhdo=,tag:BvxaKXgaskKMEGHPKsfd0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
