apiVersion: v1
kind: Secret
metadata:
    name: bridge-signal
    namespace: synapse
stringData:
    SIG_AS_TOKEN: ENC[AES256_GCM,data:9EyekfYz9XTIc86ID4sT2WVQ06Jkk9Q8VpujTzfdWejpB+eig9OoX3eooie3MeFITbVy07jElCog5ZPsDQnU8Q==,iv:Bi4r/3VFc2G3a79a+x5kYpWIXAWuNghThJ1iiot1oJM=,tag:H5pUSmP8SbuQG23yReU9FQ==,type:str]
    SIG_HS_TOKEN: ENC[AES256_GCM,data:oR04ImRUIsz3RAQBbAtfZ0V4nGRIMvPoT0gPcRjFQIlj5ERZJ6368KADc8UUfPQPSSyoRpn6LvmRqdzC5MdsBQ==,iv:5Wrt56cNOWlv4ouf4sifThDFOcwkIfaGA/mFY1e5ffo=,tag:yoYArbem1YDWZ6PUjfmwHg==,type:str]
    SIG_LP: ENC[AES256_GCM,data:mT2RncbuwfP/JhWyeTJ1eUmCpJgNy4bVRDhezJtv2iYIltBEkVzft+BTce42bfCGRaw8VIy1JrUmjUIld4MpPw==,iv:/R75PdFHpy13sak/EdxoC+EC3s7tKB9of9PNd8lrJ9s=,tag:PzjIb6p/pZisJbPE1z2VWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10c9vvuvfkflc7zypu6zm8dtw0gdn028nlr3gslt35df8vdqrap5q36xav4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkxaYWMzMXNKSEVLSVgv
            OHpBOHJFQWliT1hNa2VPL09naG9IYjB6dUI0CnArYVpndVFYKzdmUnAxQkVkODhV
            aFJ5U3J5c2NoQmJBM2J2UzV0NkU1eGMKLS0tIG9ZM3FjNnBxVTlWOVl3NGhPM0xB
            K0xCVXVCNXdjbjFydEx5ZnRGdTRTT1EKBab1xoVoWvwgraB1VhdxTkkh5D0HHm4t
            PJp4Q8rI6JXpHbA2pVq05pWLZTpjXjObU3hBrl6yz2AuCQs59STalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-06T08:45:44Z"
    mac: ENC[AES256_GCM,data:XiBJF9c4LnJuKMaXd88kZDVTMucN2u3qwFgDoqxybSxAjQmtfu72A5eBB1w9cFLj4moKzfXbsUdYanDLahn+XofQkRs3vj1/p0xLcJbSkaKmbRFYtS6jFUT0DImut1ADKxXyhr7yB7mtleENEU1OqlqimduswgxMLOttw/gqoAI=,iv:qkPqeatuNhCpNiP832lmk/xkuUGCP69ADbiCzWfSErM=,tag:YvrD1TOoyD9mDr58iR//UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
