---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: jellyfin-helm
        namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 1h
  releaseName: jellyfin
  upgrade:
    remediation:
      retries: -1
  values:
    # https://github.com/samcday/jellyfin-helm/blob/main/values.yaml
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: [jellyfin.home.samcday.com]
      paths: [/]
    persistence:
      config:
        enabled: true
        storageClass: seaweedfs-storage
      media:
        enabled: true
        storageClass: seaweedfs-storage
        size: 100Gi
