apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
configMapGenerator:
- name: jellyfin-values
  files: [values.yaml]
resources:
- ../config
- helm-release.yaml
- namespace.yaml
