# https://github.com/samcday/jellyfin-helm/blob/main/values.yaml

ingress:
  enabled: true
  ingressClassName: nginx
  hosts: [jellyfin.home.samcday.com]
  paths: [/]

persistence:
  config:
    enabled: true
    storageClass: openebs-hostpath
  media:
    enabled: true
    storageClass: openebs-hostpath
    size: 100Gi
