---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: syncthing
spec:
  chart:
    spec:
      chart: syncthing
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 3.3.0
  install:
    remediation:
      retries: -1
  interval: 1h0m0s
  releaseName: syncthing
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: syncthing-values
