# https://github.com/k8s-at-home/charts/blob/master/charts/stable/syncthing/values.yaml
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml

persistence:
  data:
    enabled: true
    storageClass: openebs-hostpath
