---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-fip-k8s
  namespace: kube-system
spec:
  chart:
    spec:
      chart: hcloud-fip-k8s
      version: 0.0.13
      sourceRef:
        kind: HelmRepository
        name: hcloud-fip-k8s
        namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 5m
  releaseName: hcloud-fip-k8s
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
  - kind: ConfigMap
    name: hcloud-fip-k8s-values
