---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: miniflux
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: morremeyer
        namespace: flux-system
      version: 5.3.1
  interval: 5m
  releaseName: miniflux
  valuesFrom:
  - kind: ConfigMap
    name: miniflux-values
