---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: miniflux
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 11.9.12
  install:
    remediation:
      retries: -1
  interval: 5m
  releaseName: postgres
  upgrade:
    remediation:
      retries: -1
  values:
    # https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
    global:
      storageClass: openebs-hostpath
    image:
      repository: postgres
      tag: 14.5-bullseye
    primary:
      initdb:
        scripts:
          miniflux.sql: |-
            create database miniflux;
            create extension hstore;
