apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bridge-signal
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bridge-signal
  serviceName: bridge-signal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bridge-signal
    spec:
      containers:
        - image: dock.mau.dev/mautrix/signal:v0.4.2
          name: mautrix-signal
          ports:
            - containerPort: 29328
            - name: metrics
              containerPort: 8001
          volumeMounts:
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
            - name: data
              mountPath: /signald_data
              subPath: signald
        - image: signald/signald:stable
          name: signald
          args:
            - -d
            - /data/signald
            - --metrics
            - -s
            - /signald/signald.sock
          ports:
            - name: signald-metrics
              containerPort: 9595
          volumeMounts:
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
        - name: litestream
          image: litestream/litestream:0.3.9
          args: ['replicate']
          volumeMounts: &litestreamvols
            - name: data
              mountPath: /data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream-signal.yml
          envFrom: &litestreamenv
            - secretRef:
                name: backup-bucket
          ports:
            - name: ls-metrics
              containerPort: 9090
      initContainers:
        - name: init-litestream-mautrix-synapse
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-signal.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-signald
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/signald/signald.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: config
          image: alpine:3
          command:
            - sh
            - -c
            - |-
              set -uexo pipefail
              mkdir -p /data/signald
              chown -R 1337:1337 /data
              sed -e "s/_AS_/$SIG_AS_TOKEN/" \
                  -e "s/_HS_/$SIG_HS_TOKEN/" \
                  -e "s/_LP_/$SIG_LP/" \
                  -e "s/_DBUSER_/$DBUSER/" \
                  -e "s/_DBPASS_/$DBPASS/" \
                  < /config-templates/mautrix-signal.yaml > /data/config.yaml
          env:
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mautrix-whatsapp-owner-user.synapse-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: mautrix-whatsapp-owner-user.synapse-db.credentials.postgresql.acid.zalan.do
                  key: password
          envFrom:
            - secretRef:
                name: bridge-signal
          volumeMounts:
            - name: config-templates
              mountPath: /config-templates
            - name: data
              mountPath: /data
      volumes:
        - name: config-templates
          configMap:
            name: config-signal
        - name: data
          emptyDir: {}
        - name: litestream-config
          configMap:
            name: litestream-config-signal
        - name: signald
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-signal
  namespace: synapse
spec:
  ports:
  - port: 29328
    protocol: TCP
    targetPort: 29328
  selector:
    app.kubernetes.io/name: bridge-signal
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bridge-signal
  namespace: synapse
spec:
  podMetricsEndpoints:
    - port: ls-metrics
    - port: metrics
      path: /
    - port: signald-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: bridge-signal
