apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bridge-telegram
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bridge-telegram
  serviceName: bridge-telegram
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bridge-telegram
    spec:
      containers:
        - image: dock.mau.dev/mautrix/telegram:v0.12.1
          name: mautrix-telegram
          ports:
            - containerPort: 29317
            - name: metrics
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
        - name: litestream
          image: litestream/litestream:0.3.9
          args: ['replicate']
          volumeMounts: &litestreamvols
            - name: data
              mountPath: /data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream-telegram.yml
          envFrom: &litestreamenv
            - secretRef:
                name: backup-bucket
          ports:
            - name: ls-metrics
              containerPort: 9090
      initContainers:
        - name: init-litestream-mautrix-telegram
          image: litestream/litestream:0.3.9
          args: [restore, -if-db-not-exists, -if-replica-exists, -v, /data/mautrix-telegram.db]
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: config
          image: alpine:3
          command:
            - sh
            - -c
            - |-
              set -uexo pipefail
              chown -R 1337:1337 /data
              sed -e "s/_AS_/$TELE_AS_TOKEN/" -e "s/_HS_/$TELE_HS_TOKEN/" -e "s/_API_ID_/$TELE_API_ID/" -e "s/_API_HASH_/$TELE_API_HASH/" < /config-templates/mautrix-telegram.yaml > /data/config.yaml
          envFrom:
            - secretRef:
                name: bridge-telegram
          volumeMounts:
            - name: config-templates
              mountPath: /config-templates
            - name: data
              mountPath: /data
      volumes:
        - name: config-templates
          configMap:
            name: config
        - name: litestream-config
          configMap:
            name: litestream-config-telegram
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-telegram
  namespace: synapse
spec:
  ports:
  - port: 29317
    protocol: TCP
    targetPort: 29317
  selector:
    app.kubernetes.io/name: bridge-telegram
