apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: synapse
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  serviceName: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
    spec:
      containers:
        - image: dock.mau.dev/mautrix/signal:v0.4.2
          name: mautrix-signal
          ports:
            - containerPort: 29328
            - name: mau-sig-metrics
              containerPort: 8001
          volumeMounts:
            - name: data
              mountPath: /db
            - name: mautrix-signal
              mountPath: /data
            - name: signald
              mountPath: /signald
            - name: data
              mountPath: /signald_data
              subPath: signald
        - image: dock.mau.dev/mautrix/telegram:v0.12.1
          name: mautrix-telegram
          ports:
            - containerPort: 29317
            - name: mau-tgm-metrics
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /db
            - name: mautrix-telegram
              mountPath: /data
        - image: signald/signald:stable
          name: signald
          args:
            - -d
            - /data/signald
            - --metrics
            - -s
            - /signald/signald.sock
          ports:
            - name: signald-metrics
              containerPort: 9595
          volumeMounts:
            - name: data
              mountPath: /data
            - name: signald
              mountPath: /signald
        - name: litestream
          image: litestream/litestream:0.3.9
          args: ['replicate']
          volumeMounts: &litestreamvols
            - name: data
              mountPath: /data
            - name: litestream-config
              mountPath: /etc/litestream.yml
              subPath: litestream.yml
          envFrom: &litestreamenv
            - secretRef:
                name: backup-bucket
          ports:
            - name: ls-metrics
              containerPort: 9090
        - image: matrixdotorg/synapse
          name: synapse
          ports:
            - name: synapse
              containerPort: 8008
            - name: syn-metrics
              containerPort: 9000
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /config/homeserver.yaml
            - name: UID
              value: "1337"
            - name: GID
              value: "1337"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: mautrix-signal
              mountPath: /mautrix-signal
            - name: mautrix-telegram
              mountPath: /mautrix-telegram
            - name: signing-key
              mountPath: /signing-key
      initContainers:
        - name: init-litestream-mautrix-synapse
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-signal.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-mautrix-telegram
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/mautrix-telegram.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-synapse
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/synapse.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: init-litestream-signald
          image: litestream/litestream:0.3.9
          args: ['restore', '-if-db-not-exists', '-if-replica-exists', '-v', '/data/signald/signald.db']
          volumeMounts: *litestreamvols
          envFrom: *litestreamenv
        - name: config
          image: alpine:3
          command:
            - sh
            - -c
            - |-
              apk add gettext
              rm -f /mautrix-signal/*
              rm -f /mautrix-telegram/*
              mkdir -p /data/media
              mkdir -p /data/signald
              chown -R 1337:1337 /data
              cp /config-templates/mautrix-signal.yaml /mautrix-signal/config.yaml
              sed -e "s/_AS_/$WA_AS_TOKEN/" -e "s/_HS_/$WA_HS_TOKEN/" < /config-templates/registration-whatsapp.yaml > /config/registration-whatsapp.yaml
              envsubst < /config-templates/mautrix-telegram.yaml > /mautrix-telegram/config.yaml
              cp /config-templates/log.yaml /config/
              envsubst < /config-templates/homeserver.yaml > /config/homeserver.yaml
          envFrom:
            - secretRef:
                name: bridge-whatsapp
            - secretRef:
                name: synapse-env
          volumeMounts:
            - name: config-templates
              mountPath: /config-templates
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: mautrix-signal
              mountPath: /mautrix-signal
            - name: mautrix-telegram
              mountPath: /mautrix-telegram
        - name: mautrix-signal-register
          image: dock.mau.dev/mautrix/signal:v0.4.0
          volumeMounts:
            - name: mautrix-signal
              mountPath: /data
        - name: mautrix-telegram-register
          image: dock.mau.dev/mautrix/telegram:v0.12.1
          volumeMounts:
            - name: mautrix-telegram
              mountPath: /data
      tolerations:
        - key: samcday.com/cloud
          operator: Exists
          effect: NoExecute
      volumes:
        - name: config-templates
          configMap:
            name: config
        - name: config
          emptyDir: {}
        - name: litestream-config
          configMap:
            name: litestream-config
        - name: mautrix-signal
          emptyDir: {}
        - name: mautrix-telegram
          emptyDir: {}
        - name: signing-key
          secret:
            secretName: signing-key
        - name: signald
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app.kubernetes.io/name: synapse
